name: Docker

on:
  push:
    branches:
      - 'master'
    paths:
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/docker.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/docker.yml'

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        if: "github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop'"
        timeout-minutes: 2
      - uses: actions/checkout@v2
        timeout-minutes: 2
      - name: docker build
        run: docker build .
